export interface CountryCode {
  code: string;   // ISO 3166-1 alpha-2
  name: string;
  dial: string;   // e.g. "+971"
}

export const COUNTRY_CODES: CountryCode[] = [
  { code: 'AE', name: 'UAE', dial: '+971' },
  { code: 'SA', name: 'Saudi Arabia', dial: '+966' },
  { code: 'QA', name: 'Qatar', dial: '+974' },
  { code: 'KW', name: 'Kuwait', dial: '+965' },
  { code: 'BH', name: 'Bahrain', dial: '+973' },
  { code: 'OM', name: 'Oman', dial: '+968' },
  { code: 'JO', name: 'Jordan', dial: '+962' },
  { code: 'LB', name: 'Lebanon', dial: '+961' },
  { code: 'IQ', name: 'Iraq', dial: '+964' },
  { code: 'YE', name: 'Yemen', dial: '+967' },
  { code: 'PS', name: 'Palestine', dial: '+970' },
  { code: 'SY', name: 'Syria', dial: '+963' },
  { code: 'EG', name: 'Egypt', dial: '+20' },
  { code: 'LY', name: 'Libya', dial: '+218' },
  { code: 'TN', name: 'Tunisia', dial: '+216' },
  { code: 'DZ', name: 'Algeria', dial: '+213' },
  { code: 'MA', name: 'Morocco', dial: '+212' },
  { code: 'SD', name: 'Sudan', dial: '+249' },
  { code: 'IN', name: 'India', dial: '+91' },
  { code: 'PK', name: 'Pakistan', dial: '+92' },
  { code: 'BD', name: 'Bangladesh', dial: '+880' },
  { code: 'LK', name: 'Sri Lanka', dial: '+94' },
  { code: 'NP', name: 'Nepal', dial: '+977' },
  { code: 'AF', name: 'Afghanistan', dial: '+93' },
  { code: 'US', name: 'United States', dial: '+1' },
  { code: 'CA', name: 'Canada', dial: '+1' },
  { code: 'GB', name: 'United Kingdom', dial: '+44' },
  { code: 'DE', name: 'Germany', dial: '+49' },
  { code: 'FR', name: 'France', dial: '+33' },
  { code: 'ES', name: 'Spain', dial: '+34' },
  { code: 'IT', name: 'Italy', dial: '+39' },
  { code: 'NL', name: 'Netherlands', dial: '+31' },
  { code: 'BE', name: 'Belgium', dial: '+32' },
  { code: 'PT', name: 'Portugal', dial: '+351' },
  { code: 'AT', name: 'Austria', dial: '+43' },
  { code: 'CH', name: 'Switzerland', dial: '+41' },
  { code: 'SE', name: 'Sweden', dial: '+46' },
  { code: 'NO', name: 'Norway', dial: '+47' },
  { code: 'DK', name: 'Denmark', dial: '+45' },
  { code: 'FI', name: 'Finland', dial: '+358' },
  { code: 'PL', name: 'Poland', dial: '+48' },
  { code: 'GR', name: 'Greece', dial: '+30' },
  { code: 'IE', name: 'Ireland', dial: '+353' },
  { code: 'TR', name: 'Turkey', dial: '+90' },
  { code: 'RU', name: 'Russia', dial: '+7' },
  { code: 'CN', name: 'China', dial: '+86' },
  { code: 'JP', name: 'Japan', dial: '+81' },
  { code: 'KR', name: 'South Korea', dial: '+82' },
  { code: 'MY', name: 'Malaysia', dial: '+60' },
  { code: 'SG', name: 'Singapore', dial: '+65' },
  { code: 'ID', name: 'Indonesia', dial: '+62' },
  { code: 'PH', name: 'Philippines', dial: '+63' },
  { code: 'TH', name: 'Thailand', dial: '+66' },
  { code: 'VN', name: 'Vietnam', dial: '+84' },
  { code: 'MM', name: 'Myanmar', dial: '+95' },
  { code: 'AU', name: 'Australia', dial: '+61' },
  { code: 'NZ', name: 'New Zealand', dial: '+64' },
  { code: 'ZA', name: 'South Africa', dial: '+27' },
  { code: 'NG', name: 'Nigeria', dial: '+234' },
  { code: 'KE', name: 'Kenya', dial: '+254' },
  { code: 'GH', name: 'Ghana', dial: '+233' },
  { code: 'TZ', name: 'Tanzania', dial: '+255' },
  { code: 'UG', name: 'Uganda', dial: '+256' },
  { code: 'BR', name: 'Brazil', dial: '+55' },
  { code: 'MX', name: 'Mexico', dial: '+52' },
  { code: 'AR', name: 'Argentina', dial: '+54' },
  { code: 'CO', name: 'Colombia', dial: '+57' },
  { code: 'CL', name: 'Chile', dial: '+56' },
  { code: 'PE', name: 'Peru', dial: '+51' },
  { code: 'IR', name: 'Iran', dial: '+98' },
  { code: 'IL', name: 'Israel', dial: '+972' },
];

export const DEFAULT_COUNTRY = COUNTRY_CODES[0]; // UAE
